### ISSUE TITLE
Protect main branch?

### ISSUE THREAD

**Issue by kt86** [matsim-vsp/bvwp-scraping#5]
@kainagel @paulheinr 
Aktuell ist der `main`-branch nicht protected. Ist das Absicht? Falls nicht, würde ich das nach eurem Go ändern.

**Comment by kainagel** [comment]
ja wäre wohl gut

On 22. Feb 2024, at 21:32, Kai Martins-Turner ***@***.***> wrote:



@kainagel<https://github.com/kainagel> @paulheinr<https://github.com/paulheinr>
Aktuell ist der main-branch nicht protected. Ist das Absicht? Falls nicht, würde ich das nach eurem Go ändern.

**Comment by kt86** [comment]
Done.
