### ISSUE TITLE
Projekt ist Fork von Pauls Repo

### ISSUE THREAD

**Issue by kt86** [matsim-vsp/bvwp-scraping#6]
Bekommen wir das aufgelöst, dass es dann eigenständig ist?
Beim Erstellen von PRs möchte er es zunächst immer in das ursprüngliche Repo bei @paulheinr packen. Das halte ich aber für mittelfristig nicht sinnvoll, dafür ist es aber fehleranfällig, weil man sich 2x konzentrieren muss, wo der PR hin soll.

Oder hat das noch einen mir aktuell nicht bekannten Grund, dass es so ist, wie es ist und so bleiben sollte?

**Comment by paulheinr** [comment]
Stimmt, das ist doof. Ich habe noch keine Admin-Rechte, kann mich dann aber darum kümmern. Reminder: https://stackoverflow.com/questions/16052477/delete-fork-dependency-of-a-github-repository

**Comment by kt86** [comment]
Damit es auch hier ist und nicht nur per Chat: Du solltest mMn die Rechte nun haben.

**Comment by paulheinr** [comment]
ich habe den Fork entfernt. damit sollte das problem nun gelöst sein.
