### ISSUE TITLE
Add CI-Testing

### ISSUE THREAD

**Issue by kt86** [matsim-vsp/bvwp-scraping#9]
Ich denke, wir sollten nun dann auch GHActions integrieren und das Bestehen der Tests dann als Voraussetzungen zum mergen der PRs machen.

Ich kann da gerne mal schauen, dass ich das analog zu anderen Repos einstelle, es sei denn @paulheinr möchte gerne.

**Comment by paulheinr** [comment]
Führe ich mit #14 ein.
